FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build

WORKDIR /app
COPY . ./

WORKDIR /app/ActualizeDb.Cli
RUN dotnet restore
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app
COPY --from=build /app/ActualizeDb.Cli/out .
ENTRYPOINT ["dotnet", "TestAnalytics.ActualizeDb.Cli.dll", "--add-predefined-projects"]
