FROM mcr-proxy.kontur.host/dotnet/sdk:9.0 AS build

WORKDIR /app
COPY . ./

WORKDIR /app/TestCity.RedirectFromSingularToNewUrl
RUN dotnet restore
RUN dotnet publish -c Release -o out

FROM mcr-proxy.kontur.host/dotnet/aspnet:9.0
WORKDIR /app

ENV ASPNETCORE_ENVIRONMENT="Production"
COPY --from=build /app/TestCity.RedirectFromSingularToNewUrl/out .
EXPOSE 8125
ENTRYPOINT ["dotnet", "Kontur.TestCity.RedirectFromSingularToNewUrl.dll"]
