FROM node:20 AS build

WORKDIR /app
COPY Front/package.json Front/package-lock.json ./
RUN npm ci --omit=dev
COPY Front/ ./
RUN npm run build -- --mode=production


FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY Front/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
