FROM node:20 AS build

WORKDIR /app
COPY Front/package.json Front/package-lock.json ./
RUN npm ci --omit=dev
COPY Front/ ./
ENV NODE_ENV=production
RUN npm run build -- --mode=production


FROM nginx:alpine
ENV GITLAB_URL=""
COPY --from=build /app/dist /usr/share/nginx/html
COPY Front/nginx.conf /etc/nginx/templates/default.conf.template
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
